version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "olivia0123"
      ACCEPT_EULA: "Y"
    ports:
      - "5432:1433"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
    driver: local